"""switch to blog models

Revision ID: a5b76ae92cc3
Revises: 13f19000b5d4
Create Date: 2024-05-11 23:40:04.018007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b76ae92cc3'
down_revision: Union[str, None] = '13f19000b5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hrs_heroes_uuid', table_name='hrs_heroes')
    op.drop_table('hrs_heroes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrs_heroes',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('mage', 'assassin', 'warrior', 'priest', 'tank', name='hrs_role'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='pk_hrs_heroes')
    )
    op.create_index('ix_hrs_heroes_uuid', 'hrs_heroes', ['uuid'], unique=True)
    # ### end Alembic commands ###
