"""posts deleted on user delete

Revision ID: a80201ab5a99
Revises: 70a8aef6c643
Create Date: 2024-05-14 00:28:57.207809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a80201ab5a99'
down_revision: Union[str, None] = '70a8aef6c643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_posts_author_uuid_users', 'posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_posts_author_uuid_users', 'posts', 'users', ['author_uuid'], ['uuid'])
    # ### end Alembic commands ###
